### ISSUE TITLE
newrelic configuration

### ISSUE THREAD

**Issue by NareshKurukuti** [jeremyharris/cakephp-newrelic#2]
**Hi jeremyharris,**
      I am new to the NewRelic Plugin, I have few questions, Can you please give me solutions to the questions?

**1**. NewRelic will be work for the Local Environment (development environment on my pc).  If yes, can you tell me how it will work and what can I do?
**2**. In your plugin, where did you configure the License key of NewRelic.  Without License Key configure, How it will be work?
**3**. I did the given steps in your plugin, I didn't understand what to do after that and how can I get the data in my NewRelic account.

Can you answer it, as soon as possible?

**Comment by jeremyharris** [comment]
1. The plugin only does anything if you have the newrelic extension installed in your php environment, otherwise it is ignored. For local development it's typically ignored because there is no newrelic extension installed.
2. I believe this is configured through php ini.
3. The newrelic extension handles this. This plugin simply renames requests in a way that makes more sense.

This plugin is very old and also only works with an old version of Cake. What this Cake plugin does might not even be relevant anymore, I'm not sure. Just keep that in mind.

I would suggest installing and configuring the appropriate php newrelic extension and see what data flows into newrelic first.

Let me know if you have anymore questions. I'll try my best to answer them.

Good luck!
